version: '3'
services:
  frontend:
    image: nginx:alpine  
    ports:
      - '3000:3000'  
    volumes:
      - ./frontend/srgan-website/build:/usr/share/nginx/html 

  backend:
    build:
      context: ./backend/js_server
      dockerfile:  ../../Dockerfile
    ports:
      - '8501:8501'